// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syiapgirlrircolsrwqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aWFwZ2lybHJpcmNvbHNyd3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDU2NTMsImV4cCI6MjA2NzIyMTY1M30.-dxKKmBQG_uZSz0cPMHjpxIAeEyAd1zADO6-nJvRg6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});